#ici ce trouve le master raspberry


print("                 , .-.-,_,")
print("                 )`-.>'` (")
print("                /     `\  |")
print("                |       | |")
print("                 \     / /")
print("                 `=(\ /.=`")
print("                  `-;`.-'")
print("                    `)|     ,")
print("                     ||  .-'|")
print("                   ,_||  \_,/")
print("             ,      \|| .'")
print("             |\|\  , ||/")
print("            ,_\` |/| |Y_,")
print("             '-.'-._\||/   ")          
print("                >_.-`Y|")
print("                ` .-'||'-.")
print("                  \'----'/")
print("                   |:.  |")
print("                   |::. |")
print("                  /::::  \ ")
print("                .:::'     '.")
print("               /:::         \ ")
print("              ;:::'          ;")
print("              |:::           |")
print("              |:::           |")
print("              |:::           |")
print("              ;:::           ;")
print("              \:::.          /")
print("               ':::..      .'")
print("                `""-----""`   Projet Gabi")

#Initiation 
#Connexion 